services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "555:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # image: next-server
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # volumes:
    #   - .:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
    external: true